In [51]:
#String test
num = [3, 45, 83, 21]
print(num)

[3, 45, 83, 21]


In [49]:
#String test
letters = ['w', 'r', 'a']
print(letters)

['w', 'r', 'a']


In [55]:
#Task 1 Write a program that allows you to enter 4 numbers 
#Can you only save one argument per write request? Can you save integers here? 
numbers = open('numbers.txt', 'w')
numbers.write('3, 45, 83, 21')
numbers.close()



In [39]:
letters = open("letters.txt", "w")
letters.write('w, r, a')
letters.close()

In [11]:
#Task 2 Write a program to ask a student for their percentage mark and convert this to a grade. Use function for conversion.
#Function 
def mark_grade(percentage):
    if (percentage >=80) and (percentage <=100):
        return 'A*'
    elif (percentage >=70) and (percentage <80):
        return 'A'
    elif (percentage >=60) and (percentage <70):
        return'B'
    elif (percentage >=50) and (percentage <60):
        return 'C'
    elif (percentage >=40) and (percentage <50):
        return 'D'
    elif (percentage >=0) and (percentage <40):
        return'E'
    else:
        return 'Invalid mark'
       

   

In [12]:
#Task 2 Write a program to ask a student for their percentage mark and convert this to a grade. Use function for conversion.
percentage = int(input('Enter your precentage mark:'))
print('Your percentage mark is', percentage,'% and your grade is', mark_grade(percentage))






    

Your percentage mark is 65 % and your grade is B


In [1]:
#Ask the user for their target grade and print this with their 
#I have left some of my working for this question but I have been unable to complete the extension task. 
# I found that I had an issue with having the actual grade as a string and then not being able to compare this with the 
#target grade. For example, I wanted to do-- if target > mark_grade: print(Your mark is higher than...) but of course 
#they are both strings so I couldn't think of a way to compare them. Below is some of my ideas...
target = input('What is your target grade(capitals only):')
if target == 'A*':
   percentage = (percentage >=80) and (percentage <=100)
if target == 'A':
    percentage = (percentage >=70) and (percentage <80)
elif target == 'B':
    percentage = (percentage >=60) and (percentage <70)
elif target == 'C':
    percentage = (percentage >=50) and (percentage <60)
elif target == 'D':
    percentage = (percentage >=40) and (percentage <50)
elif target == 'E':
    percentage = (percentage >=0) and (percentage <40)
else: 
     ''

percentage = input('Type in your current percentage mark:')
print(mark_grade(percentage))



NameError: name 'percentage' is not defined

In [82]:
#Extension to Task 2
percentage = int(input('What is your current percentage mark?:'))
Target = input('What is you target grade?:')
print('Your current grade is', mark_grade(percentage), 'Your target is', Target)
if mark_grade(percentage) >= Target:
    print('Congratulations! Your current grade is above your target!')
if mark_grade(percentage) == Target:
    print('You are currently at your target grade.')
if mark_grade(percentage) <= Target:
    print ('Your current grade is below your target.')
else:
    print('')



Your current grade is A* Your target is B
Your current grade is below your target.


In [101]:
if target == 'A':
    (percentage >=70) and (percentage <80)
elif target == 'B':
    (percentage >=60) and (percentage <70)
elif target == 'C':
    (percentage >=50) and (percentage <60)
elif target == 'D':
    (percentage >=40) and (percentage <50)
elif target == 'E':
    (percentage >=0) and (percentage <40)
else: 
    ''



In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\scare\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7])
print(array)

[1 2 3 4 5 6 7]


In [6]:
import numpy as np 
rando=np.random.rand(2,3)
print(rando)

[[0.14237879 0.30682085 0.45962855]
 [0.94254091 0.56118709 0.67062665]]


In [23]:
import numpy as np
a = np.arange (1,10).reshape (3,3) 
b = np.arange (10,19).reshape (3,3) 
c = np.dot(a, b)
print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [26]:
#Task 1: Create a 1D array of numbers from 0 to 9
import numpy as np
oneD_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(oneD_array)

[1 2 3 4 5 6 7 8 9]


In [37]:
#Task 2: Create a 3×3 NumPy array of all Boolean value Trues
import numpy as np
bool_ones = np.ones((3, 3), dtype=bool) 
print(bool_ones)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [38]:
#Task 3: Extract all odd numbers from array of 1-10
import numpy as np
odd = np.arange(1, 11, 2)
print(odd)

[1 3 5 7 9]


In [43]:
# Task 4: Replace all odd numbers in an array of 1-10 with the value -1
import numpy as np
minus1 = np.array([1, 2, 3, 4, 5, 6, 7, 9, 10])
minus1[minus1%2 == 1] = -1
print(minus1)



[-1  2 -1  4 -1  6 -1 -1 10]


In [59]:
# Task 5:  Convert a 1D array to a 2D array with 2 rows
import numpy as np
convert1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
convert2 = convert1.reshape(4, 3)
print(convert2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
# Task 6: Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
array_1 = np.arange(1, 10).reshape (3,3)
array_2 = np.arange(11, 20).reshape (3,3)
print(array_1)
print(array_2)
dot = np.dot(array_1, array_2)
print(dot)
sum=np.sum(dot)
print(sum)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
2079


In [77]:
# Extension: Create the following pattern without hardcoding. Use only NumPy functions.
code = np.array([1, 2, 3])
print(code)
np.r_[np.repeat(code, 3), np.tile(code, 3)]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [84]:
#Extension: In two arrays a ( 1,2,3,4,5) and b ( 5,6,7,8,9) – remove all repeating items present in array b.
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a,b)





array([1, 2, 3, 4])

In [92]:
#Extension: Get all items between 3 and 7 from a and b and sum them together.
a1 =np.where((a>=3) & (a<=7))
b1 = np.where((a>=3) & (a<=7))
print(a1, b1)

(array([2, 3, 4], dtype=int64),) (array([2, 3, 4], dtype=int64),)
